// SurveySchema - the structured schema generated by LLM from raw questionnaire
export interface SurveySchema {
  version: string;
  sections: SurveySection[];
  metadata: {
    estimatedDuration: number; // minutes
    totalQuestions: number;
    language: string;
  };
}

export interface SurveySection {
  id: string;
  title: string;
  description: string;
  order: number;
  questions: SurveyQuestion[];
}

export interface SurveyQuestion {
  id: string;
  text: string;
  type: 'open_ended' | 'rating' | 'multiple_choice' | 'yes_no';
  required: boolean;
  followUpRules: FollowUpRule[];
  extractionFields: ExtractionField[];
}

export interface FollowUpRule {
  condition: string; // natural language condition
  question: string;
  maxDepth: number; // max follow-up rounds (default 2)
}

export interface ExtractionField {
  key: string;
  type: 'string' | 'number' | 'boolean' | 'string[]' | 'object';
  description: string;
}

export interface SurveyContext {
  product: string;
  targetUsers: string;
  focusAreas: string[];
  additionalContext?: string;
}

export interface SurveySettings {
  maxDurationMinutes: number;
  language: string;
  tone: 'formal' | 'casual' | 'neutral';
  llmConfig?: LLMConfigOverride;
}

// Per-survey LLM configuration override
export interface LLMConfigOverride {
  provider?: 'anthropic' | 'anthropic-messages' | 'openai-compatible';
  baseUrl?: string;
  apiKey?: string;
  model?: string;
  temperature?: number;
}

// ─── Survey Agent ──────────────────────────────────────────────────────────────
// Each published survey is a complete "Agent" with AI-generated configuration

export interface SurveyAgent {
  // The structured survey schema
  schema: SurveySchema;

  // AI-generated interview prompt template
  promptTemplate: InterviewPromptTemplate;

  // Interactive skill definitions (which questions use cards)
  interactiveSkills: InteractiveSkillConfig[];

  // Behavior configuration
  behavior: AgentBehaviorConfig;
}

export interface InterviewPromptTemplate {
  // Role description for the interviewer agent
  roleDescription: string;
  // Opening message / greeting template
  openingMessage: string;
  // Closing message / thank-you template
  closingMessage: string;
  // Custom behavior rules (in addition to system defaults)
  customRules: string[];
}

export interface InteractiveSkillConfig {
  // Which question this skill is attached to
  questionId: string;
  sectionId: string;
  // Card type to render
  cardType: 'nps' | 'rating' | 'multiple_choice' | 'multi_select' | 'yes_no' | 'likert' | 'slider';
  // Card-specific configuration
  cardConfig: Record<string, unknown>;
}

export interface AgentBehaviorConfig {
  maxFollowUpRounds: number;
  detectImpatience: boolean;
  allowSkipping: boolean;
  adaptiveDepth: boolean; // adjust follow-up depth based on response quality
  transitionStyle: 'smooth' | 'direct'; // how to transition between sections
}
